# environment.yml

name: low-rank-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Core depencies from pyproject.toml
  - python>=3.10
  - numpy>=1.21
  - scipy>=1.7

  # Development tools
  - pip
  - build # for package building
  - twine # for uploading to PyPi
  - pytest # for testing the code
  - pytest-cov # for test coverage review
  - ipykernel # for using Jupyter notebooks

  # Sphinx documentation dependencies
  - sphinx>=7.0
  - sphinx_rtd_theme  # Read the Docs theme
  - sphinx-autodoc-typehints  # Better type hint support
  - myst-parser  # Optional: support Markdown in addition to RST

